    let base = {
        "storeID": "{{storeID}}",
        "listingID": "{{listingID}}",
        "viewName": "{{viewName}}",
        "language": "{{language}}",
        "storeDMA": "{{storeDMA}}",
        "storePostalCode": "{{storePostalCode}}",
        "storeName": "{{storeName}}",
        "retailerID": "{{retailerID}}",
        "retailerName": "{{retailerName}}",
        "siteName": "{{siteName}}",
        "navOrigin": "{{navOrigin}}",
        "navMethod": "{{navMethod}}",
        "viewMode": "{{viewMode}}",
        "viewTitle": "{{viewTitle}}",
        "content_group1": "{{content_group1}}",
        "page_path": "{{page_path}}",
        "event_label": "{{event_label}}",
        "event_action": "{{event_action}}",
        "event_category": "{{event_category}}",
    }

    let localTags = {
        "add_to_cart": {
            "storeID": "{{storeID}}",
            "listingID": "{{listingID}}",
            "viewName": "{{viewName}}",
            "language": "{{language}}",
            "storeDMA": "{{storeDMA}}",
            "storePostalCode": "{{storePostalCode}}",
            "storeName": "{{storeName}}",
            "retailerID": "{{retailerID}}",
            "retailerName": "{{retailerName}}",
            "siteName": "{{siteName}}",
            "navOrigin": "{{navOrigin}}",
            "navMethod": "{{navMethod}}",
            "viewMode": "{{viewMode}}",
            "viewTitle": "{{viewTitle}}",
            "content_group1": "{{content_group1}}",
            "page_path": "{{page_path}}",
            "event_label": "{{event_label}}",
            "event_action": "{{event_action}}",
            "event_category": "{{event_category}}",
        },
    }
